stages:
  - test
# Set up cache, so we have to run composer update between builds, speeding it up!
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - vendor/
test:
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  stage: test
  services:
    - mysql:5.7
  variables:
    MYSQL_DATABASE: "test"
    MYSQL_ROOT_PASSWORD: "secret"

  script:
    - composer update --no-interaction --no-progress  --prefer-dist --optimize-autoloader --ignore-platform-reqs
    - cp .env.testing .env
    - php artisan key:generate
    - php artisan config:cache
    - php artisan migrate --seed
    - php artisan storage:link
    - php artisan serve &
    - vendor/bin/phpunit

