<?php

namespace Tests\Feature;

use App\Affiliate;
use App\Deal;
use App\Product;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class DealsTest extends TestCase
{
  Use RefreshDatabase,WithFaker;
  protected $affiliate;
   protected function setUp(): void
   {
       parent::setUp(); // TODO: Change the autogenerated stub
       $this->affiliate = factory(Affiliate::class)->create();
   }

   public function test_affiliate_can_add_deals(){
     $data = [
        'product_id'=>factory(Product::class)->create()->id,
        'price'=>$this->faker->randomNumber(),
        'begin_on'=>$this->faker->dateTime,
        'end_at'=>$this->faker->dateTime,
     ] ;
//
     $this->actingAs($this->affiliate,'affiliate')->post(action('Affiliate\DealsController@store'),$data)
         ->assertRedirect()->assertSessionHasNoErrors();
     $this->assertDatabaseHas('deals',$data);
   }


   public function test_affiliate_can_update_deals(){
     $deal=factory(Deal::class)->create();
     $attributes=[
       'product_id'=>factory(Product::class)->create()->id,
         'price'=>$this->faker->randomFloat(),
         'begin_on'=>$this->faker->date('Y-m-d'),
         'end_at'=>$this->faker->date('Y-m-d'),
     ];
//     assertSessionhasNoErro=checks validator
//       assertredirect checks the return type might be return redirect back or a view
    $this->actingAs($this->affiliate,'affiliate')->post(action('Affiliate\DealsController@update',$deal->id),$attributes)
        ->assertSessionHasNoErrors()->assertRedirect();
    $deal=$deal->refresh();
    $this->assertEquals($deal->name,$attributes['price']);
    $this->assertEquals($deal->name,$attributes['begin_on']);
    $this->assertEquals($deal->name,$attributes['end_at']);


   }

}
