<?php

namespace Tests\Feature;

use App\Product;
use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class WishListTest extends TestCase
{
  use RefreshDatabase,WithFaker;

  protected $user;

  protected function setUp(): void
  {
      parent::setUp(); // TODO: Change the autogenerated stub
      $this->user = factory(User::class)->create();
  }


      /*
       * this function tests if a product is saved in the wish list
       */
      public function test_user_can_add_product_to_wishList(){
          $product = factory(Product::class)->create();

          $data = [
            'user_id'=>$this->user->id,
          ];
          $this->actingAs($this->user)->post(action('ProductsController@addToWishList',$product->id),$data)
              ->assertRedirect()->assertSessionHasNoErrors();
          $this->assertDatabaseHas('wish_list',$data);

  }

}
