<?php

namespace Tests\Feature;

use App\Admin;
use App\Affiliate;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AffiliatesTest extends TestCase
{
 use WithFaker,RefreshDatabase;
 protected $admin;

 protected function setUp(): void
 {
     parent::setUp(); // TODO: Change the autogenerated stub
     $this->admin = factory(Admin::class)->create();

 }

    /*
     * This function tests if the index method in Affiliates controller retrieves
     * all affiliates in database properly
     */
    public function test_admin_can_view_affiliates(){
      $this->withExceptionHandling();
      $affiliate = factory(Affiliate::class)->create();
      $this->actingAs($this->admin,'admin')->get(action('Admin\AffiliatesController@index'))
          ->assertSessionHasNoErrors()
          ->assertSuccessful()
          ->assertSee($affiliate->name);
    }

    /*
    * This function tests if the method changeStatus in affiliatesController works properly
    */

    public function test_admin_can_changeStatus(){
        $this->withExceptionHandling();
        $affiliate = factory(Affiliate::class)->create();
        $data = [
           'status'=>$this->faker->boolean,
        ];
        $this->actingAs($this->admin,'admin')->post(action('Admin\AffiliatesController@changeStatus',$affiliate->id),$data)
            ->assertSessionHasNoErrors()->assertRedirect();
        $affiliate = $affiliate->fresh();
        $this->assertNotEquals($affiliate->status,$data['status']);
    }
}
